OPTIONS
(
SKIP = 1
ROWS = 50000
DIRECT = TRUE
INDEX_OPTION = 2
CHARACTER_CODE='UTF-8'
ERRORS = 100
)
LOAD DATA
INFILE 'E:/RHPT/TOPI1/BAS_COMPANY.csv'
BADFILE 'E:/RHPT/TOPI1/BAS_COMPANY.bad'
APPEND
INTO TABLE SYSDBA.BAS_COMPANY
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
(
  ID CHAR NULLIF ID = '',
  COMPANYNO CHAR NULLIF COMPANYNO = '',
  COMPANYNAME CHAR NULLIF COMPANYNAME = '',
  SHORTNAME CHAR NULLIF SHORTNAME = '',
  MNEMONIC CHAR NULLIF MNEMONIC = '',
  CONTACT CHAR NULLIF CONTACT = '',
  CONTACTPHONENO CHAR NULLIF CONTACTPHONENO = '',
  FAXNUMBER CHAR NULLIF FAXNUMBER = '',
  ADDRESS CHAR NULLIF ADDRESS = '',
  ZIPCODE CHAR NULLIF ZIPCODE = '',
  ADMINISTRATORCODE CHAR NULLIF ADMINISTRATORCODE = '',
  NOTE CHAR NULLIF NOTE = '',
  STATUS INTEGER NULLIF STATUS = '',
  CREATORID CHAR NULLIF CREATORID = '',
  CREATEDTIME TIMESTAMP 'YYYY-MM-DD HH:MI:SS.FF' NULLIF CREATEDTIME = '',
  MODIFIERID CHAR NULLIF MODIFIERID = '',
  MODIFIEDTIME TIMESTAMP 'YYYY-MM-DD HH:MI:SS.FF' NULLIF MODIFIEDTIME = '',
  BGIMGPATH CHAR NULLIF BGIMGPATH = '',
  INTRO CHAR NULLIF INTRO = '',
  LOGOPATH CHAR NULLIF LOGOPATH = '',
  DEFAULTPASSWORD CHAR NULLIF DEFAULTPASSWORD = '',
  SKYLIGHTURL CHAR NULLIF SKYLIGHTURL = '',
  DELETERID CHAR NULLIF DELETERID = '',
  DELETEDTIME TIMESTAMP 'YYYY-MM-DD HH:MI:SS.FF' NULLIF DELETEDTIME = '',
  ISDELETED INTEGER NULLIF ISDELETED = '',
  COMPANY_TYPE_ID CHAR NULLIF COMPANY_TYPE_ID = ''
)
